<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN3leyfm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN3leyfm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerN3leyfm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerN3leyfm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerN3leyfm\appProdProjectContainer([
    'container.build_hash' => 'N3leyfm',
    'container.build_id' => '06914348',
    'container.build_time' => 1615305661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN3leyfm');
